[project]
name = "vhap"
version = "0.0.1"
description = "vanutp hosting admin panel"
requires-python = ">=3.11"
authors = [
  {name = "Ivan Filipenkov", email = "hello@vanutp.dev"},
]

dependencies = [
  "fastapi",
  "uvicorn",
  "python-multipart",
  "pydantic",
  "pydantic-settings",
  "httpx",
  "aiodocker",
  "authlib",
  "pyyaml",
]

[project.scripts]
vhapd = "vhapd:main"
vhap = "vhap:main"
