keys:
  - &tardis age15th0378hqw9c8uddwler6edsh39wc88h0r4smv8j8x694ywk89nsswmjwf
  - &tardis-user age1p8dqe95af3u38m4edd8vvrpgsrxywhr4kn7kk53hs4j450mv8ymslyla5w
  - &dull_vessel age1qxqskh7c42mwgrrn025spgvavu88zwgrv3kzax9captf30adxapsv2na0l
  - &dull_vessel-user age1wejr7c52k33sekl5x3zdaqtgayap629d42y60f8cwc6pu3lp7exsltc83d
  - &s1 age1uwzr96dww90a25dqrq7jmpygnal6p4ksmqehkj7tt5qn6jrda4xq4gn2sf
  - &p1 age1lx2w9ru4cn75fg9chc6sk4aqrrpg5y7nwnz43uum7fuvns4yuuvsf9w7h8
creation_rules:
  - path_regex: dull-vessel/(home|system)/secrets.yml$
    key_groups:
    - age:
      - *dull_vessel
      - *dull_vessel-user
  - path_regex: servers/p1/system/secrets.yml$
    key_groups:
    - age:
      - *dull_vessel-user
      - *p1
