# Generated by update-qt.py
# Do not modify
pkgs: let
  repository = pkgs.fetchFromGitHub {
    owner = "desktop-app";
    repo = "patches";
    rev = "407b8ebd38d8d0a3787da9dd815465fd40480a1b";
    hash = "sha256-bQsvLqh6Pg4D9NGY9/QuwTgw5dXc8tvhOWdM/wQK5oY=";
  };
  qtbase = pkgs.kdePackages.qtbase.overrideAttrs (orig: {
    patches =
      orig.patches
      ++ [
        "${repository}/qtbase_6.7.1/0001-spellcheck-underline-from-chrome.patch"
        "${repository}/qtbase_6.7.1/0002-improve-apostrophe-processing.patch"
        "${repository}/qtbase_6.7.1/0003-allow-creating-floating-panels-macos.patch"
        "${repository}/qtbase_6.7.1/0004-fix-file-dialog-on-windows.patch"
        "${repository}/qtbase_6.7.1/0005-fix-launching-mail-program-on-windows.patch"
        "${repository}/qtbase_6.7.1/0006-save-dirtyopaquechildren.patch"
        "${repository}/qtbase_6.7.1/0007-always-use-xft-font-conf.patch"
        "${repository}/qtbase_6.7.1/0008-catch-cocoa-dock-menu.patch"
        "${repository}/qtbase_6.7.1/0009-fix-race-in-windows-timers.patch"
        "${repository}/qtbase_6.7.1/0010-nicer-platformtheme-choosing.patch"
        "${repository}/qtbase_6.7.1/0011-reset-current-context-on-error.patch"
        "${repository}/qtbase_6.7.1/0012-reset-opengl-widget-on-context-loss.patch"
        "${repository}/qtbase_6.7.1/0013-no-jpeg-chroma-subsampling.patch"
        "${repository}/qtbase_6.7.1/0014-convert-qimage-to-srgb.patch"
        "${repository}/qtbase_6.7.1/0015-lcms2.patch"
        "${repository}/qtbase_6.7.1/0016-better-color-scheme-support.patch"
        "${repository}/qtbase_6.7.1/0017-translucent-captioned-window-on-windows.patch"
        "${repository}/qtbase_6.7.1/0018-allow-bordered-translucent-macos.patch"
        "${repository}/qtbase_6.7.1/0019-better-open-url-linux.patch"
        "${repository}/qtbase_6.7.1/0020-follow-highdpi-rounding-policy-for-platform-dpr.patch"
        "${repository}/qtbase_6.7.1/0021-fill-transparent-hidpi-backing-store.patch"
        "${repository}/qtbase_6.7.1/0022-fix-backing-store-rhi-unneeded-copy.patch"
        "${repository}/qtbase_6.7.1/0023-fix-backing-store-opengl-subimage-unneeded-copy.patch"
        "${repository}/qtbase_6.7.1/0024-portal-proxy-resolver.patch"
        "${repository}/qtbase_6.7.1/0025-fix-focus-in-hidden-window.patch"
        "${repository}/qtbase_6.7.1/0026-fix-only-emoji-line.patch"
        "${repository}/qtbase_6.7.1/0027-fix-rtl-cursor-move-up.patch"
      ];
  });
  qtshadertools = pkgs.kdePackages.qtshadertools.override {inherit qtbase;};
  qtlanguageserver = pkgs.kdePackages.qtlanguageserver.override {inherit qtbase;};
  qtdeclarative = pkgs.kdePackages.qtdeclarative.override {inherit qtbase qtlanguageserver qtshadertools;};
in [
  qtbase
  (pkgs.kdePackages.qtsvg.override {inherit qtbase;})
  (pkgs.kdePackages.qtimageformats.override {inherit qtbase;})
  ((pkgs.kdePackages.qtwayland.overrideAttrs {
      patches = [
        "${repository}/qtwayland_6.7.1/0001-always-fractional-scale.patch"
        "${repository}/qtwayland_6.7.1/0002-offload-transparency-filling-to-hidpi.patch"
        "${repository}/qtwayland_6.7.1/0003-fix-gtk4-embedding.patch"
        "${repository}/qtwayland_6.7.1/0004-QWaylandShmBackingStore-Preserve-buffer-contents-bet.patch"
        "${repository}/qtwayland_6.7.1/0005-avoid-needlessly-initiailizing-opengl.patch"
        "${repository}/qtwayland_6.7.1/0006-fix-media-viewer-on-gnome.patch"
        "${repository}/qtwayland_6.7.1/0007-owning-rhi-backing-store.patch"
      ];
    })
    .override {inherit qtbase qtdeclarative;})
]
