# Generated by update-qt.py
# Do not modify
pkgs: let
  repository = pkgs.fetchFromGitHub {
    owner = "desktop-app";
    repo = "patches";
    rev = "940c3070d28ea2dca370a28ecb0500148473044b";
    hash = "sha256-DbqAPlSXnEWz7nprYdWLIh2ORubQOO0kAP4whFvbV7M=";
  };
  qtbase = pkgs.kdePackages.qtbase.overrideAttrs (orig: {
    patches =
      orig.patches
      ++ [
        "${repository}/qtbase_6.8.0/0001-spellcheck-underline-from-chrome.patch"
        "${repository}/qtbase_6.8.0/0002-improve-apostrophe-processing.patch"
        "${repository}/qtbase_6.8.0/0003-allow-creating-floating-panels-macos.patch"
        "${repository}/qtbase_6.8.0/0004-fix-file-dialog-on-windows.patch"
        "${repository}/qtbase_6.8.0/0005-fix-launching-mail-program-on-windows.patch"
        "${repository}/qtbase_6.8.0/0006-save-dirtyopaquechildren.patch"
        "${repository}/qtbase_6.8.0/0007-always-use-xft-font-conf.patch"
        "${repository}/qtbase_6.8.0/0008-catch-cocoa-dock-menu.patch"
        "${repository}/qtbase_6.8.0/0009-fix-race-in-windows-timers.patch"
        "${repository}/qtbase_6.8.0/0010-nicer-platformtheme-choosing.patch"
        "${repository}/qtbase_6.8.0/0011-reset-current-context-on-error.patch"
        "${repository}/qtbase_6.8.0/0012-reset-opengl-widget-on-context-loss.patch"
        "${repository}/qtbase_6.8.0/0013-no-jpeg-chroma-subsampling.patch"
        "${repository}/qtbase_6.8.0/0014-convert-qimage-to-srgb.patch"
        "${repository}/qtbase_6.8.0/0015-lcms2.patch"
        "${repository}/qtbase_6.8.0/0016-translucent-captioned-window-on-windows.patch"
        "${repository}/qtbase_6.8.0/0017-allow-bordered-translucent-macos.patch"
        "${repository}/qtbase_6.8.0/0018-better-open-url-linux.patch"
        "${repository}/qtbase_6.8.0/0019-follow-highdpi-rounding-policy-for-platform-dpr.patch"
        "${repository}/qtbase_6.8.0/0020-let-platform-backing-store-scale-transparency-filling.patch"
        "${repository}/qtbase_6.8.0/0021-fix-backing-store-rhi-unneeded-copy.patch"
        "${repository}/qtbase_6.8.0/0022-portal-proxy-resolver.patch"
        "${repository}/qtbase_6.8.0/0023-fix-focus-in-hidden-window.patch"
        "${repository}/qtbase_6.8.0/0024-fix-only-emoji-line.patch"
        "${repository}/qtbase_6.8.0/0025-fix-rtl-cursor-move-up.patch"
        "${repository}/qtbase_6.8.0/0026-xcb-provide-xkb-state.patch"
        "${repository}/qtbase_6.8.0/0027-windows-fullscreen-with-mask.patch"
        "${repository}/qtbase_6.8.0/0028-accept-only-cf_hdrop-as-uri-list.patch"
      ];
  });
  qtshadertools = pkgs.kdePackages.qtshadertools.override {inherit qtbase;};
  qtlanguageserver = pkgs.kdePackages.qtlanguageserver.override {inherit qtbase;};
  qtdeclarative = pkgs.kdePackages.qtdeclarative.override {inherit qtbase qtlanguageserver qtshadertools;};
in [
  qtbase
  (pkgs.kdePackages.qtsvg.override {inherit qtbase;})
  (pkgs.kdePackages.qtimageformats.override {inherit qtbase;})
  ((pkgs.kdePackages.qtwayland.overrideAttrs {
      patches = [
        "${repository}/qtwayland_6.8.0/0001-always-fractional-scale.patch"
        "${repository}/qtwayland_6.8.0/0002-scale-transparency-filling.patch"
        "${repository}/qtwayland_6.8.0/0003-fix-gtk4-embedding.patch"
        "${repository}/qtwayland_6.8.0/0004-owning-rhi-backing-store.patch"
        "${repository}/qtwayland_6.8.0/0005-fix-egl-compositor-shutdown.patch"
        "${repository}/qtwayland_6.8.0/0006-compositor-xkb-state-from-platform.patch"
      ];
    })
    .override {inherit qtbase qtdeclarative;})
]
